services:
  thaboralame_front:
    container_name: thaboralame_front
    build:
      context: ./thaboralame_front
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./thaboralame_front:/app
      - /app/node_modules

  backend:
    container_name: thaboralame_back
    build:
      context: ./thaboralame_back
      dockerfile: Dockerfile.dev
    volumes:
      - ./thaboralame_back:/var/www/html
    ports:
      - "8082:8080"
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
    depends_on:
      - mysql

  mysql:
    container_name: thaboralame_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: