services:

  #######################
  # Frontend
  #######################

  frontend:
    container_name: thaboralame_front
    build:
      context: ./thaboralame_front
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3002
    volumes:
      - ./thaboralame_front:/app
    env_file:
      - .env 

  #######################
  # Gateway
  #######################

  gateway:
    container_name: thaboralame_gateway
    build:
      context: ./thaboralame_gateway
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    volumes:
      - ./thaboralame_gateway:/app
    env_file:
      - .env
    depends_on:
      - user
      - auth

  #######################
  # Auth
  #######################

  auth:
    container_name: thaboralame_auth
    build:
      context: ./thaboralame_auth
      dockerfile: Dockerfile.dev
    ports:
      - 8082:8082
    volumes:
      - ./thaboralame_auth:/app
    env_file:
      - .env

  #######################
  # User
  #######################

  user:
    container_name: thaboralame_user
    build:
      context: ./thaboralame_user
      dockerfile: Dockerfile.dev
    ports:
      - 8083:8083
    volumes:
      - ./thaboralame_user:/app
    env_file:
      - .env

  #######################
  # Networks
  #######################

networks:
  default:
    external: true
    name: thaboralame_mysql_network