services:
  frontend:
    container_name: thaboralame_front
    build:
      context: ./thaboralame_front
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3002
    volumes:
      - ./thaboralame_front:/app
    env_file:
      - .env 

  auth:
    container_name: thaboralame_auth
    build:
      context: ./thaboralame_auth
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    volumes:
      - ./thaboralame_auth:/app
      - target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth_db:3306/${MYSQL_AUTH_DATABASE}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - auth_db

  auth_db:
    container_name: thaboralame_auth_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_AUTH_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - thaboralame_auth_db:/var/lib/mysql

volumes:
  thaboralame_front:
  thaboralame_auth_db:
  target: